quickly added form body support
DimensionDataCBUSydney/PowerShell.REST.API pull request #3
Opened 2017-03-08 04:32 UTC by stopthatastronaut

As before, might need some tidying up - my C# chops aren't what they once were

One use case I had was to handle Slack outgoing webhooks. Unfortunately, they POST as x-www-form-urlencoded, not JSON.

So I quickly added some code for that

2017-03-08 04:41 UTC, tintoy commented
That's great - I think we can probably detect `x-www-form-urlencoded` by the `Content-Type` header BTW.

2017-03-08 04:42 UTC, tintoy commented
Give me a couple of minutes and I'll pull this in.

2017-03-08 04:47 UTC, stopthatastronaut commented
Yeah, header would be more reliable I reckon. It _was_ a quick & dirty change ;)

2017-03-08 05:00 UTC, tintoy requested changes
Need to think about the required-parameters change, it has the potential to break existing clients...

2017-03-08 05:00 UTC, tintoy commented on Controllers/GenericController.cs
> -						throw new MissingParametersException("Cannot find all parameters required.");
Maybe check if the missing parameter is optional (`!Required`) and only throw if it's not?

2017-03-08 05:00 UTC, tintoy commented on Controllers/GenericController.cs
> -						throw new MissingParametersException("Cannot find all parameters required.");
If we allow required parameters to go through to Powershell without values then the call is going to fail anyway...

2017-03-08 05:47 UTC, tintoy commented
Ok @stopthatastronaut - I've pushed some minor changes to enable optional properties (in the config file, mark the parameter with `IsOptional="true"`.

Can you have a look and let me know if this works for you?

2017-03-08 05:51 UTC, tintoy commented
You can basically just tack on

```csharp
else if (requestContentType == "x-www-form-urlencoded")
{
	NameValueCollection formFields = await Request.Content.ReadAsFormDataAsync();
	foreach (string formFieldName in formFields.AllKeys)
	{
		commandParameters.Add(
			key: formFieldName,
			value: formFields[formFieldName]
		);
	}
}
```

2017-03-09 00:06 UTC, tintoy commented
Do you have time to resolve the merge conflict, @stopthatastronaut? If not, let me know and I'll manually alter the PR to fix it.

2017-03-09 00:24 UTC, merged

2017-03-09 00:25 UTC, tintoy commented
Never mind - I manually merged it. Thanks for your contribution! 😄